// src/lib/mathSymbols.js
// رموز ومصطلحات رياضية لمرحلة الثانوية (الصفوف الأول والثاني والثالث)،
// مبنية على مفردات منهج الرياضيات السعودي: الجبر والدوال، الهندسة،
// حساب المثلثات (بالترميز العربي «جا/جتا/ظا» المعتمد في الكتاب المدرسي)،
// الإحصاء والاحتمالات، والتفاضل والتكامل لمسار ثالث ثانوي العلمي.

export const MATH_SYMBOL_GROUPS = [
  {
    key: "ops",
    title: "العمليات والأُسس",
    items: [
      { sym: "±", label: "زائد أو ناقص" },
      { sym: "×", label: "ضرب" },
      { sym: "÷", label: "قسمة" },
      { sym: "=", label: "يساوي" },
      { sym: "≠", label: "لا يساوي" },
      { sym: "≈", label: "يساوي تقريبًا" },
      { sym: "≡", label: "مطابق لـ" },
      { sym: "√", label: "جذر تربيعي" },
      { sym: "∛", label: "جذر تكعيبي" },
      { sym: "∜", label: "جذر رباعي" },
      { sym: "x²", label: "أس 2 — تربيع" },
      { sym: "x³", label: "أس 3 — تكعيب" },
      { sym: "xⁿ", label: "أس n" },
      { sym: "x⁻¹", label: "أس سالب 1 — المقلوب" },
      { sym: "xₙ", label: "دليل سفلي n" },
      { sym: "%", label: "نسبة مئوية" },
    ],
  },
  {
    key: "fractions",
    title: "الكسور والنسب",
    items: [
      { sym: "½", label: "نصف" },
      { sym: "⅓", label: "ثلث" },
      { sym: "⅔", label: "ثلثان" },
      { sym: "¼", label: "ربع" },
      { sym: "¾", label: "ثلاثة أرباع" },
      { sym: "⅕", label: "خمس" },
      { sym: "⅙", label: "سدس" },
      { sym: "⅛", label: "ثمن" },
      { sym: "∶", label: "نسبة بين كميتين" },
      { sym: "‰", label: "نسبة بالألف" },
    ],
  },
  {
    key: "compare",
    title: "المتباينات والمقارنة",
    items: [
      { sym: "<", label: "أصغر من" },
      { sym: ">", label: "أكبر من" },
      { sym: "≤", label: "أصغر من أو يساوي" },
      { sym: "≥", label: "أكبر من أو يساوي" },
      { sym: "≪", label: "أصغر كثيرًا من" },
      { sym: "≫", label: "أكبر كثيرًا من" },
      { sym: "∝", label: "يتناسب طرديًا مع" },
    ],
  },
  {
    key: "sets",
    title: "المجموعات والمنطق",
    items: [
      { sym: "∈", label: "ينتمي إلى" },
      { sym: "∉", label: "لا ينتمي إلى" },
      { sym: "⊂", label: "مجموعة جزئية من" },
      { sym: "⊆", label: "مجموعة جزئية من أو تساويها" },
      { sym: "⊄", label: "ليست مجموعة جزئية من" },
      { sym: "∪", label: "اتحاد مجموعتين" },
      { sym: "∩", label: "تقاطع مجموعتين" },
      { sym: "∖", label: "الفرق بين مجموعتين" },
      { sym: "∅", label: "المجموعة الخالية" },
      { sym: "ℝ", label: "مجموعة الأعداد الحقيقية" },
      { sym: "ℕ", label: "مجموعة الأعداد الطبيعية" },
      { sym: "ℤ", label: "مجموعة الأعداد الصحيحة" },
      { sym: "ℚ", label: "مجموعة الأعداد النسبية" },
      { sym: "∀", label: "لكل" },
      { sym: "∃", label: "يوجد" },
      { sym: "∴", label: "إذن / لذلك" },
      { sym: "∵", label: "لأن" },
      { sym: "⇒", label: "يؤدي إلى (استنتاج)" },
      { sym: "⇔", label: "إذا وفقط إذا" },
    ],
  },
  {
    key: "algebra",
    title: "الجبر والدوال",
    items: [
      { sym: "ƒ(x)", label: "دالة في x" },
      { sym: "f⁻¹(x)", label: "الدالة العكسية" },
      { sym: "Δ", label: "دلتا — مميز المعادلة أو التغيّر" },
      { sym: "∑", label: "مجموع حدود (سيجما)" },
      { sym: "∏", label: "جداء حدود (پاي)" },
      { sym: "|x|", label: "القيمة المطلقة" },
      { sym: "∞", label: "لا نهاية" },
      { sym: "→", label: "يؤول إلى" },
      { sym: "↦", label: "تقابل (x يؤول إلى y)" },
      { sym: "i", label: "الوحدة التخيلية" },
    ],
  },
  {
    key: "geometry",
    title: "الهندسة",
    items: [
      { sym: "∠", label: "زاوية" },
      { sym: "△", label: "مثلث" },
      { sym: "▭", label: "مستطيل" },
      { sym: "◻", label: "مربع" },
      { sym: "⬠", label: "خماسي" },
      { sym: "⬡", label: "سداسي" },
      { sym: "∥", label: "يوازي" },
      { sym: "⊥", label: "يعامد" },
      { sym: "≅", label: "تطابق (مثلثان متطابقان)" },
      { sym: "∼", label: "تشابه (مثلثان متشابهان)" },
      { sym: "°", label: "درجة (قياس زاوية)" },
      { sym: "⌢", label: "قوس" },
      { sym: "⊙", label: "دائرة" },
      { sym: "π", label: "باي — النسبة التقريبية" },
    ],
  },
  {
    key: "trig",
    title: "حساب المثلثات",
    items: [
      { sym: "جا", label: "جيب الزاوية (sin)" },
      { sym: "جتا", label: "جيب تمام الزاوية (cos)" },
      { sym: "ظا", label: "ظل الزاوية (tan)" },
      { sym: "ظتا", label: "ظل تمام الزاوية (cot)" },
      { sym: "قا", label: "قاطع الزاوية (sec)" },
      { sym: "قتا", label: "قاطع تمام الزاوية (csc)" },
      { sym: "جا⁻¹", label: "معكوس الجيب (sin⁻¹)" },
      { sym: "جتا⁻¹", label: "معكوس جيب التمام (cos⁻¹)" },
      { sym: "ظا⁻¹", label: "معكوس الظل (tan⁻¹)" },
      { sym: "θ", label: "ثيتا — رمز الزاوية" },
      { sym: "π", label: "باي" },
    ],
  },
  {
    key: "calculus",
    title: "التفاضل والتكامل",
    items: [
      { sym: "نها", label: "النهاية (lim)" },
      { sym: "lim", label: "النهاية (Limit)" },
      { sym: "dx", label: "تفاضل x" },
      { sym: "dy", label: "تفاضل y" },
      { sym: "d/dx", label: "المشتقة بالنسبة إلى x" },
      { sym: "f′(x)", label: "المشتقة الأولى للدالة" },
      { sym: "f″(x)", label: "المشتقة الثانية للدالة" },
      { sym: "∫", label: "تكامل" },
      { sym: "∫∫", label: "تكامل مزدوج" },
      { sym: "∂", label: "تفاضل جزئي" },
      { sym: "Δx", label: "التغيّر في x" },
      { sym: "∞", label: "لا نهاية" },
    ],
  },
  {
    key: "stats",
    title: "الإحصاء والاحتمال",
    items: [
      { sym: "P(A)", label: "احتمال وقوع الحدث A" },
      { sym: "C(n,r)", label: "التوافيق" },
      { sym: "P(n,r)", label: "التباديل" },
      { sym: "n!", label: "مضروب العدد" },
      { sym: "x̄", label: "الوسط الحسابي" },
      { sym: "μ", label: "الوسط الحسابي للمجتمع" },
      { sym: "σ", label: "الانحراف المعياري" },
      { sym: "σ²", label: "التباين" },
      { sym: "∑", label: "مجموع القيم (سيجما)" },
    ],
  },
  {
    key: "greek",
    title: "الحروف اليونانية",
    items: [
      { sym: "α", label: "ألفا" },
      { sym: "β", label: "بيتا" },
      { sym: "γ", label: "غاما" },
      { sym: "δ", label: "دلتا صغيرة" },
      { sym: "Δ", label: "دلتا كبيرة" },
      { sym: "ε", label: "إبسيلون" },
      { sym: "θ", label: "ثيتا" },
      { sym: "λ", label: "لامدا" },
      { sym: "μ", label: "ميو" },
      { sym: "π", label: "باي" },
      { sym: "ρ", label: "رو" },
      { sym: "σ", label: "سيجما صغيرة" },
      { sym: "Σ", label: "سيجما كبيرة" },
      { sym: "τ", label: "تاو" },
      { sym: "φ", label: "فاي" },
      { sym: "ω", label: "أوميغا صغيرة" },
      { sym: "Ω", label: "أوميغا كبيرة" },
    ],
  },
];

// تطبيع بسيط يتجاهل التشكيل وألِف الوصل، فتُطابق الكلمة أيًا كانت صيغتها
// في جدول «المواد» (رياضيات 1، الرياضيات، Mathematics...).
export function isMathSubject(name) {
  if (!name) return false;
  const n = String(name).replace(/[ً-ٰٟ]/g, "").replace(/[إأآا]/g, "ا");
  return /رياضيات/.test(n) || /\bmath(s|ematics)?\b/i.test(String(name));
}
